eureka:
  instance:
    lease-expiration-duration-in-seconds: 2  #如果2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-renewal-interval-in-seconds: 1   #每间隔1s，向服务端发送一次心跳，证明自己依然“存活”
    
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    #这是Eureka-Client向Eureka-Service注册的端口
      
server:
  port: 8765        #Eureka-Client的端口为8765
spring:
  application:
    name: service-hi  #以后的服务与服务之间相互调用一般都是根据这个name，即该名字是Eureka-Client向Eureka-Client注册的名字