eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 5003
spring:
  application:
    name: Gateway-Service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411
zuul:
  routes:
    hiapi:                        #这里是自己定义
      path: /hiapi/**             #url中以/hiapi开头的请求都会分发到Eureka-Client服务上
      serviceId: User-Service       #serviceId会启动ribbon的负载均衡
                                  #如果不想启用负载均衡，去掉serviceId，改用配置url: http://localhost:8763,会怼到指定的端口
   